// 组件库按需引入
import {
    ElIcon,
    ElLoading,
    ElPagination,
    ElDialog,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElInput,
    ElInputNumber,
    ElRadio,
    ElRadioGroup,
    ElRadioButton,
    ElCheckbox,
    ElCheckboxButton,
    ElCheckboxGroup,
    ElSwitch,
    ElSelect,
    ElOption,
    ElOptionGroup,
    ElButton,
    ElButtonGroup,
    ElTable,
    ElTableColumn,
    ElDatePicker,
    ElTimeSelect,
    ElTimePicker,
    ElPopover,
    ElTooltip,
    ElMessageBox,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElForm,
    ElFormItem,
    ElTabs,
    ElTabPane,
    ElTag,
    ElTree,
    ElAlert,
    ElNotification,
    ElSlider,
    // Row,
    // Col,
    ElUpload,
    ElProgress,
    // Spinner,
    ElMessage,
    ElBadge,
    // Card,
    ElRate,
    // Steps,
    // Step,
    ElCarousel,
    ElScrollbar,
    ElCarouselItem,
    // Collapse,
    // CollapseItem,
    ElCascader,
    // ColorPicker,
    // Transfer,
    // Container,
    // Header,
    // Aside,
    // Main,
    // Footer,
    // Timeline,
    // TimelineItem,
    ElLink,
    ElDivider,
    ElImage,
    ElCalendar,
    ElBacktop,
    ElInfiniteScroll,
    ElPageHeader,
    ElCascaderPanel,
    ElAvatar,
    ElDrawer,
    ElPopconfirm,
    // Skeleton,
    // SkeletonItem,
    // Empty,
    // Descriptions,
    // DescriptionsItem,
    // Result
} from 'element-plus';

const components = [
    ElIcon,
    ElLoading,
    ElPagination,
    ElDialog,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElInput,
    ElInputNumber,
    ElRadio,
    ElRadioGroup,
    ElRadioButton,
    ElCheckbox,
    ElCheckboxButton,
    ElCheckboxGroup,
    ElSwitch,
    ElSelect,
    ElOption,
    ElOptionGroup,
    ElButton,
    ElButtonGroup,
    ElTable,
    ElTableColumn,
    ElDatePicker,
    ElTimeSelect,
    ElTimePicker,
    ElPopover,
    ElTooltip,
    ElMessageBox,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElForm,
    ElFormItem,
    ElTabs,
    ElTabPane,
    ElTag,
    ElTree,
    ElAlert,
    ElNotification,
    ElSlider,
    // Row,
    // Col,
    ElUpload,
    ElProgress,
    // Spinner,
    ElMessage,
    ElBadge,
    // Card,
    ElRate,
    // Steps,
    // Step,
    ElCarousel,
    ElScrollbar,
    ElCarouselItem,
    // Collapse,
    // CollapseItem,
    ElCascader,
    // ColorPicker,
    // Transfer,
    // Container,
    // Header,
    // Aside,
    // Main,
    // Footer,
    // Timeline,
    // TimelineItem,
    ElLink,
    ElDivider,
    ElImage,
    ElCalendar,
    ElBacktop,
    ElInfiniteScroll,
    ElPageHeader,
    ElCascaderPanel,
    ElAvatar,
    ElDrawer,
    ElPopconfirm,
    // Skeleton,
    // SkeletonItem,
    // Empty,
    // Descriptions,
    // DescriptionsItem,
    // Result
]
// ElementPlus 图标
import * as Icons from '@element-plus/icons-vue'

// 加载全局样式
import '@/core/assets/global.css';

// 预安装插件
export default {
    install: function (app, opts = {}) {
        // 安装ElementPlus
        components.forEach(component => {
            app.use(component);
        });

        for (let i in Icons) {
            app.component(Icons[i].name, Icons[i]);
        }

    }
}